### ISSUE TITLE
Planteamiento inicial

### ISSUE THREAD

**Issue by greyox97** [SantiagoMSalazar/agile_exam#11]
# Workflow, visión y metáfora del proyecto

@SantiagoMSalazar (Big boss) y @jluSalazar  (Coach) plantean los siguientes documentos iniciales: 

**Workflow**

Flujo de trabajo que se llevará para el desarrollo por cada iteración.
  
**Visión**
- Objetivo general.
- Objetivos específicos.
- Alcance.
- Requisitos generales.

**Team**
- Metáfora: descripción general de la aplicación
- Roles.

**Comment by SantiagoMSalazar** [comment]
WorkFlow Completado y trabajado con el Coach @jluSalazar
